# build on all pushes
trigger:
  branches:
    include:
      - '*'

stages:
  - stage: Build
    jobs:
      - job: Build_Docker_Image
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Docker@2
          displayName: Build Docker Image
          inputs:
            command: build
            arguments:
              "-t azure-pipelines-linux-agent"
            tags: |
              dev
        - task: Docker@2
          displayName: Login to Docker Hub
          inputs:
            command: login
            containerRegistry: dockerhub
        - task: Docker@2
          displayName: Push image to Docker Hub
          inputs:
            command: push
            containerRegistry: dockerhub
            repository: andrewconnell/azure-pipelines-linux-agent
            tags: |
              dev