# build on all pushes
trigger:
  branches:
    include:
      - '*'

stages:
  - stage: Build
    jobs:
      - job: Build_Docker_Image
        pool:
          name: Hosted Ubuntu 1604
        steps:
        - task: Docker@2
          displayName: Build Docker image
          inputs:
            command: build
            arguments:
              "-t andrewconnell/azure-pipelines-linux-agent"
            tags: |
              dev-service
        - script: docker save andrewconnell/azure-pipelines-linux-agent | gzip > $(Build.ArtifactStagingDirectory)/azure-pipelines-linux-agent.tar.gz
          displayName: Saving Docker image
        - publish: $(Build.ArtifactStagingDirectory)/azure-pipelines-linux-agent.tar.gz
          displayName: Publishing Docker image
          artifact: docker-image
  - stage: Deploy
    jobs:
      - job: Deploy_DockerHub
        pool:
          name: Hosted Ubuntu 1604
        steps:
        - download: current
          displayName: Downloading Docker image
          artifact: docker-image
        - script: docker load < $(Pipeline.Workspace)/docker-image/azure-pipelines-linux-agent.tar.gz
          displayName: Load Docker image
        - task: Docker@2
          displayName: Login to Docker Hub
          inputs:
            command: login
            containerRegistry: dockerhub
        - task: Docker@2
          displayName: Push image to Docker
          inputs:
            command: push
            containerRegistry: dockerhub
            repository: andrewconnell/azure-pipelines-linux-agent
            tags: |
              dev-service